name: "Destroy Infrastructure"

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_USE_OIDC: true
  TF_VAR_datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
  TF_VAR_datadog_app_key: ${{ secrets.DATADOG_APP_KEY }}
  TF_VAR_admin_object_id: ${{ secrets.TF_VAR_ADMIN_OBJECT_ID }}

jobs:
  destroy_development:
    name: "Destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Destroy
        run: terraform destroy 
